#!/bin/bash
# Quick test checklist for API format fixes

echo "🧪 API Format Fix - Quick Test Checklist"
echo "=========================================="
echo ""
echo "Prerequisites:"
echo "  [  ] Backend running on http://localhost:8000"
echo "  [  ] Frontend running on http://localhost:5173"
echo "  [  ] Logged in as admin@example.com / admin123"
echo ""
echo "Test 1: Dashboard Project Count"
echo "--------------------------------"
echo "  [  ] Go to Dashboard"
echo "  [  ] Check 'Total Projects' card"
echo "  [  ] Expected: Shows actual count (NOT 0)"
echo ""
echo "Test 2: Create Project"
echo "---------------------"
echo "  [  ] Go to Projects page"
echo "  [  ] Click '+ New Project'"
echo "  [  ] Enter name and description"
echo "  [  ] Click Create"
echo "  [  ] Expected: Project appears in list"
echo "  [  ] Expected: Dashboard count increases"
echo ""
echo "Test 3: Delete Project"
echo "---------------------"
echo "  [  ] Go to Projects page"
echo "  [  ] Click delete button on a project"
echo "  [  ] Confirm deletion"
echo "  [  ] Expected: Project removed from list"
echo "  [  ] Expected: Dashboard count decreases"
echo "  [  ] Expected: No errors in console"
echo ""
echo "Test 4: Dashboard Statistics"
echo "---------------------------"
echo "  [  ] Create a project"
echo "  [  ] Upload a data file"
echo "  [  ] Create a run"
echo "  [  ] Go to Dashboard"
echo "  [  ] Click '🔄 Refresh Stats'"
echo "  [  ] Expected: All cards show correct numbers"
echo "       - Total Projects: Should match actual"
echo "       - Data Files: Should show uploaded files"
echo "       - Runs: Should show created runs"
echo ""
echo "Test 5: Browser DevTools Check"
echo "------------------------------"
echo "  [  ] Open DevTools (F12) → Network tab"
echo "  [  ] Create a project"
echo "  [  ] Check POST /projects/ request"
echo "       Expected: Status 201 Created"
echo "  [  ] Delete a project"
echo "  [  ] Check DELETE /projects/{id} request"
echo "       Expected: Status 204 No Content"
echo "       Expected: No response body"
echo ""
echo "Test 6: Multiple Operations"
echo "--------------------------"
echo "  [  ] Create 3 projects"
echo "  [  ] Delete 1 project"
echo "  [  ] Update 1 project"
echo "  [  ] Go to Dashboard"
echo "  [  ] Expected: Count = 2"
echo "  [  ] Expected: Recent Projects shows 2 items"
echo ""
echo "Test 7: Error Handling"
echo "---------------------"
echo "  [  ] Try to delete non-existent project (via URL)"
echo "  [  ] Expected: Error message shown"
echo "  [  ] Try to create project with empty name"
echo "  [  ] Expected: Validation error"
echo ""
echo "=========================================="
echo "All tests passed? ✅"
echo "If any test fails, check:"
echo "  - Browser console for errors"
echo "  - Network tab for API responses"
echo "  - Backend logs for server errors"
echo ""
